# Generated by Django 3.0.2 on 2020-06-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='negative_marks',
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='no_of_sections',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Section'),
        ),
    ]
