# Generated by Django 3.0.2 on 2020-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200529_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='negative_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=4),
        ),
    ]
