# Generated by Django 3.0.2 on 2020-05-28 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_student_exam_external_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='sections',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='section_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='section_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student_exam',
            name='external_identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student_response',
            unique_together={('student_exam', 'question')},
        ),
    ]
