# Generated by Django 3.0.2 on 2020-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200601_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
