# Generated by Django 3.0.2 on 2020-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200529_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_code',
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
    ]
