# Generated by Django 3.0.2 on 2020-05-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200528_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='duration',
            new_name='duration_per_section',
        ),
    ]
