# Generated by Django 3.0.2 on 2020-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200529_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_exam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_exam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
