# Generated by Django 3.0.6 on 2020-06-02 20:55

from django.db import migrations, models
import django.db.models.deletion
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200601_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcteredSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=exam.models.ProcteredSS.file_path_img)),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Student_Exam')),
            ],
        ),
    ]
