# Generated by Django 3.0.6 on 2020-06-02 21:11

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_procteredss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procteredss',
            name='img',
            field=models.ImageField(upload_to=exam.models.ProcteredSS.file_path_img),
        ),
    ]
