# Generated by Django 3.0.6 on 2020-06-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20200602_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_exam',
            name='ss',
        ),
    ]
