# Generated by Django 3.0.6 on 2020-06-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_student_exam_ss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_response',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
