# Generated by Django 3.0.6 on 2020-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200604_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_response',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
