# Generated by Django 3.0.6 on 2020-06-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_student_exam_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_duration',
        ),
    ]
